http:
  port: "8081"
  
indian:
  host: "proxy-cabs-app.us-e2.cloudhub.io"
  port: "80"
  basepath: "/"
  protocol: "HTTP"
  client_id: "3b029e9276e5418bae87b8b4afb42b5b"
  client_secret: "387F2FE9AaA7471096efAAe96b31e69B"
  
training:
  host: "mu.learn.mulesoft.com"
  port: "80"
  basepath: "/"
  
delta:
  wsdl: "http://mu.learn.mulesoft.com/delta?wsdl"
  service: "TicketServiceService"
  port: "TicketServicePort"